-- ============================================================
-- TennisPro: drills table + 250 drills seed
-- Run this in Supabase SQL Editor (https://app.supabase.com)
-- ============================================================

CREATE TABLE IF NOT EXISTS public.drills (
  id            UUID        DEFAULT gen_random_uuid() PRIMARY KEY,
  created_at    TIMESTAMPTZ DEFAULT NOW(),
  name          TEXT        NOT NULL,
  description   TEXT,
  type          TEXT        NOT NULL CHECK (type IN ('forehand','backhand','serve','volley','footwork','return','groundstrokes','match play')),
  level         TEXT        NOT NULL CHECK (level IN ('beginner','intermediate','advanced')),
  group_size    TEXT        NOT NULL CHECK (group_size IN ('individual','pairs','group')),
  duration_min  INTEGER     DEFAULT 10,
  diagram_type  TEXT        NOT NULL DEFAULT 'baseline_rally'
);

ALTER TABLE public.drills ENABLE ROW LEVEL SECURITY;

-- Allow authenticated users to read all drills
CREATE POLICY "authenticated users can read drills"
  ON public.drills FOR SELECT
  TO authenticated
  USING (true);

-- ============================================================
-- SEED: 250 drills
-- ============================================================

INSERT INTO public.drills (name, description, type, level, group_size, duration_min, diagram_type) VALUES

-- ==================== FOREHAND (32) ====================
('Cross-Court Forehand Rally','Keep the ball deep and consistent cross-court using a full forehand swing. Focus on spin and depth over winners.','forehand','beginner','pairs',10,'crosscourt_fh'),
('Forehand Down the Middle','Drive the ball through the center of the court, minimizing angles. Ideal for warm-up and consistency building.','forehand','beginner','pairs',10,'baseline_rally'),
('Open Stance Forehand','Practice hitting forehands from an open stance, rotating hips and shoulders fully through contact.','forehand','beginner','individual',10,'crosscourt_fh'),
('Forehand Topspin Starter','Learn to brush up the back of the ball to generate topspin. Use a low-to-high swing path.','forehand','beginner','individual',10,'crosscourt_fh'),
('Slow-Ball Forehand Control','Feed slow, low balls and return with controlled, flat forehands to a target cone.','forehand','beginner','pairs',10,'baseline_rally'),
('Forehand Target Practice','Place cones in the corners of the court and aim each forehand at a specific target.','forehand','beginner','pairs',15,'crosscourt_fh'),
('Forehand Warm-Up Rally','Gentle cross-court forehand exchange to activate muscles and calibrate ball-striking timing.','forehand','beginner','pairs',8,'crosscourt_fh'),
('Basket Feed Forehand','Coach feeds balls from a basket; player hits 20 forehands per set focusing on consistent contact.','forehand','beginner','individual',10,'crosscourt_fh'),
('Forehand Coordination Drill','Drop-and-hit drill focusing on racket path, contact point, and follow-through shape.','forehand','beginner','individual',10,'crosscourt_fh'),
('Deuce Side Rally','Both players stay on the deuce side hitting only cross-court forehands in a sustained rally.','forehand','beginner','pairs',12,'crosscourt_fh'),
('Inside-Out Forehand','Move around the backhand and rip an inside-out forehand to the deuce corner. Essential pattern.','forehand','intermediate','pairs',12,'inside_out'),
('Inside-In Forehand','After loading the inside-out, disguise and go inside-in down the line to wrong-foot the opponent.','forehand','intermediate','pairs',12,'inside_in'),
('Forehand Approach Shot','Hit a short ball with a punched forehand and close the net for a first volley.','forehand','intermediate','pairs',12,'approach_net'),
('Running Forehand Wide','Sprint to a wide forehand, recover, and rebuild. Simulates real match pressure.','forehand','intermediate','pairs',15,'defensive_reset'),
('Heavy Topspin Forehand','Exaggerate the low-to-high swing to create heavy topspin. Aim for 1.5 m above the net.','forehand','intermediate','pairs',12,'crosscourt_fh'),
('Forehand Angle Shot','Create a sharp cross-court angle by contacting the ball early and rotating hips aggressively.','forehand','intermediate','pairs',12,'crosscourt_fh'),
('Forehand Swinging Volley','Step inside the baseline and take the ball on the rise for a swinging forehand volley.','forehand','intermediate','pairs',10,'approach_net'),
('Forehand Counter-Punch','Return a deep, heavy ball with a flat counter-punch down the line.','forehand','intermediate','pairs',12,'dtl_fh'),
('Two-Ball Forehand Combo','Hit two consecutive forehands: first cross-court, then down the line on the same rally.','forehand','intermediate','pairs',15,'dtl_fh'),
('Forehand Under Pressure','Opponent hits wide then deep; player must reset and attack with the next forehand.','forehand','intermediate','pairs',15,'defensive_reset'),
('High Kick Forehand Return','Return high kick serves with a forehand, absorbing the bounce and redirecting cross-court.','forehand','intermediate','pairs',12,'crosscourt_fh'),
('Forehand Pinch Shot','From an inside-in position, hit a sharp angle forehand that lands near the singles sideline.','forehand','intermediate','group',12,'crosscourt_fh'),
('Forehand Return of Serve','Step in and attack the serve with an aggressive forehand return cross-court or down the line.','forehand','advanced','pairs',15,'return_cc'),
('Forehand Winner Finish','After a short ball setup, put away a forehand winner to either corner from inside the baseline.','forehand','advanced','pairs',15,'dtl_fh'),
('Forehand Passing Shot','Opponent approaches net; hit a low, dipping forehand passing shot cross-court or down the line.','forehand','advanced','pairs',15,'crosscourt_fh'),
('Snap Forehand Winner','Short, compact swing; snap through the ball for a flat, penetrating winner.','forehand','advanced','pairs',12,'dtl_fh'),
('Forehand in Motion','Hit a quality forehand while running at full speed, maintaining balance and spin.','forehand','advanced','individual',12,'defensive_reset'),
('Offensive Forehand from Defense','Recover from a defensive position and transition to offense with a redirected forehand.','forehand','advanced','pairs',15,'defensive_reset'),
('Pro Pattern Play','Deuce side: cross-court forehand, inside-out forehand, inside-in forehand. 3-shot pattern.','forehand','advanced','pairs',15,'inside_out'),
('Forehand Deception Shot','Prepare for one direction and at the last moment redirect the forehand to wrong-foot the opponent.','forehand','advanced','pairs',15,'crosscourt_fh'),
('High-Ball Forehand Attack','Jump and strike a high forehand aggressively above shoulder height for an outright winner.','forehand','advanced','pairs',12,'crosscourt_fh'),
('Forehand Drop Shot Setup','Draw opponent to the net with a heavy forehand then execute a precise forehand drop shot.','forehand','advanced','pairs',15,'drop_shot'),

-- ==================== BACKHAND (30) ====================
('Cross-Court Backhand Rally','Sustain a cross-court backhand rally from the ad side, focusing on depth and topspin.','backhand','beginner','pairs',10,'crosscourt_bh'),
('Two-Handed Backhand Basics','Learn the two-handed grip and swing for consistent backhand drives down the middle.','backhand','beginner','individual',10,'baseline_rally'),
('One-Handed Backhand Slice','Develop the slice backhand as a defensive and approach weapon. Focus on under-spin contact.','backhand','beginner','individual',10,'crosscourt_bh'),
('Backhand Topspin Introduction','Brush up the ball with the two-hander to generate topspin on the backhand side.','backhand','beginner','pairs',10,'crosscourt_bh'),
('Backhand Target Feeding','Coach feeds to the backhand; player returns to cone targets on the backhand diagonal.','backhand','beginner','individual',10,'crosscourt_bh'),
('Backhand Down the Middle','Drive two-handed backhands through the center of the court to build depth habits.','backhand','beginner','pairs',10,'baseline_rally'),
('Ad Side Cross-Court Rally','Both players on ad side exchanging cross-court backhands. Deep and consistent.','backhand','beginner','pairs',12,'crosscourt_bh'),
('Backhand Warm-Up','Gentle backhand exchange to warm up the shoulder, arms, and timing.','backhand','beginner','pairs',8,'crosscourt_bh'),
('Basket Feed Backhand','Coach feeds from basket; player strikes 20 backhands focusing on contact and follow-through.','backhand','beginner','individual',10,'crosscourt_bh'),
('Slice Backhand Approach','Hit a low, skidding slice backhand approach shot and follow into the net.','backhand','intermediate','pairs',12,'approach_net'),
('Down-the-Line Backhand','Step around and rip a backhand down the line, surprising the opponent who expects cross-court.','backhand','intermediate','pairs',12,'dtl_bh'),
('Backhand Counter-Rally','Engage in a high-intensity cross-court backhand exchange, gradually increasing pace each shot.','backhand','intermediate','pairs',15,'crosscourt_bh'),
('Backhand Angle Shot','Create a severe angle by contacting the ball early and redirecting sharply cross-court.','backhand','intermediate','pairs',12,'crosscourt_bh'),
('Two-Hander on the Run','Sprint to a wide backhand and still land the shot cross-court deep.','backhand','intermediate','pairs',15,'defensive_reset'),
('Backhand Approach + Volley','Slice approach off the backhand side, close to net, and put away a volley.','backhand','intermediate','pairs',15,'approach_volley'),
('Backhand Topspin Passing Shot','Hit a heavy topspin backhand past a net-rushing opponent.','backhand','intermediate','pairs',12,'crosscourt_bh'),
('Backhand Pattern: CC then DTL','First backhand cross-court (to open court), second backhand down the line (winner).','backhand','intermediate','pairs',15,'crosscourt_bh'),
('One-Hander Topspin Drive','Develop a topspin one-handed backhand drive from behind the baseline.','backhand','intermediate','individual',12,'dtl_bh'),
('Backhand Heavy Rally','Exchange heavy topspin backhands cross-court, each player trying to push the other deeper.','backhand','intermediate','pairs',15,'crosscourt_bh'),
('Backhand Under Pressure','Defend a wide backhand then redirect the recovery shot deep cross-court.','backhand','intermediate','pairs',15,'defensive_reset'),
('Backhand Winner Down the Line','Setup cross-court then explode into a backhand winner down the line.','backhand','advanced','pairs',15,'dtl_bh'),
('Backhand Return of Serve','Step in and redirect a serve aggressively with the backhand cross-court or down the line.','backhand','advanced','pairs',15,'return_cc'),
('Backhand Passing Shot','From a wide defensive position, hit a precise passing shot past the net player.','backhand','advanced','pairs',15,'dtl_bh'),
('Backhand Drop Shot','Disguise a backhand drop shot using the same preparation as a drive.','backhand','advanced','pairs',12,'drop_shot'),
('Backhand Lob on the Run','When pulled wide, throw up a topspin lob off the backhand side to reset the point.','backhand','advanced','pairs',15,'lob_overhead'),
('Backhand Inside-Out','Move around to the backhand and hit inside-out to the deuce corner.','backhand','advanced','pairs',12,'crosscourt_bh'),
('High Backhand Finish','Strike a high ball on the backhand side aggressively, stepping in and driving through.','backhand','advanced','pairs',12,'crosscourt_bh'),
('Backhand Deception','Prepare a cross-court backhand and redirect down the line at the last moment.','backhand','advanced','pairs',15,'dtl_bh'),
('Backhand Power Rally','Both players hit maximum-effort topspin backhands cross-court. Aim for depth over pace.','backhand','advanced','pairs',12,'crosscourt_bh'),
('Backhand Half-Court Pattern','Alternate slice and topspin backhands from the ad side, hitting all balls to the same target.','backhand','advanced','pairs',15,'half_court'),

-- ==================== SERVE (28) ====================
('Serve Motion Basics','Learn the full trophy position and swing path without a ball. Shadow swing 20 repetitions.','serve','beginner','individual',10,'serve_t_d'),
('Flat Serve to T','Hit flat serves targeting the T from the deuce side. Focus on toss placement and snap.','serve','beginner','individual',10,'serve_t_d'),
('Flat Serve Wide Deuce','Target the wide area of the deuce service box with flat, aggressive serves.','serve','beginner','individual',10,'serve_wide_d'),
('Second Serve Topspin Intro','Learn the kick serve motion: toss behind the head, brush up and over the ball.','serve','beginner','individual',10,'serve_t_d'),
('Serve + Recovery','After each serve, recover to the T and shadow the return before repeating.','serve','beginner','individual',10,'serve_t_d'),
('Ad Side Wide Serve','Target the wide corner from the ad side to pull the opponent off the court.','serve','beginner','individual',10,'serve_wide_ad'),
('Ad Side T Serve','Serve directly to the T from the ad side, targeting the opponent''s backhand.','serve','beginner','individual',10,'serve_t_ad'),
('Serve Consistency Challenge','Aim for 80% first serve percentage hitting to a designated box half. Track misses.','serve','beginner','individual',12,'serve_t_d'),
('Kick Serve Mechanics','Focus on the extreme upward brush on the ball at contact to generate heavy kick.','serve','intermediate','individual',12,'serve_t_ad'),
('Slice Serve Wide Deuce','Brush around the ball at contact to generate lateral kick into the deuce corner.','serve','intermediate','individual',12,'serve_wide_d'),
('Body Serve to Jam','Target the opponent''s hip to jam their swing on the return.','serve','intermediate','pairs',12,'serve_body'),
('Serve + 1 Attack','Serve to a target, then attack the return with a forehand to a cone. Serves as a pattern.','serve','intermediate','pairs',15,'serve_t_d'),
('Serve + Volley','Serve and immediately rush to the net for a first volley. Classic net-approach pattern.','serve','intermediate','pairs',15,'serve_wide_d'),
('Second Serve Pressure','Hit only second serves (kick or slice) and aim for consistent deep placement.','serve','intermediate','individual',12,'serve_t_ad'),
('Ad Side Kick Serve','Kick serve from the ad side bouncing high to the opponent''s backhand.','serve','intermediate','individual',12,'serve_t_ad'),
('Deuce Side Pattern: Wide then T','Alternate wide and T serves from the deuce side to move the returner.','serve','intermediate','pairs',15,'serve_wide_d'),
('Serve + Return Practice','One player serves, one returns. Rotate after 5 serves. Focus on placement over pace.','serve','intermediate','pairs',15,'serve_t_d'),
('Kick Serve + Net Rush','Hit a high-kicking second serve then charge the net and put away the next ball.','serve','intermediate','pairs',15,'serve_t_ad'),
('Precision Serve Challenge','Place 4 cones in service box corners. Serve 20 balls, score points for cone hits.','serve','intermediate','individual',15,'serve_t_d'),
('Ace Hunt Drill','Serve 10 first serves to each of 4 targets. Count aces and unreturnable serves.','serve','advanced','individual',15,'serve_t_d'),
('Serve to Open Court','Serve wide, anticipate the return direction, and attack with the next groundstroke.','serve','advanced','pairs',15,'serve_wide_d'),
('Kick Serve to Backhand + Attack','High kick to backhand, opponent pops it up, player finishes with forehand.','serve','advanced','pairs',15,'serve_t_ad'),
('Slice Serve Ad Side Swinger','Swing the slice serve so it drifts into the body from the ad side.','serve','advanced','individual',12,'serve_wide_ad'),
('Serve Pattern Recognition','Coach calls wide/T/body after toss. Server adjusts mid-motion. Trains deception.','serve','advanced','individual',15,'serve_t_d'),
('Second Serve Under Pressure','Hit 10 consecutive kick serves into a small target zone. Reset after any miss.','serve','advanced','individual',12,'serve_t_ad'),
('Power Serve Speed Set','Three sets of 5 maximum-effort flat serves. Record and compare speeds across sets.','serve','advanced','individual',10,'serve_t_d'),
('Serve + Approach Combo','Serve wide, opponent returns, approach the short ball and close to net.','serve','advanced','pairs',15,'approach_net'),
('In-and-Out Serve Pattern','Alternate wide and body serves from both sides to constantly change angles.','serve','advanced','pairs',15,'serve_body'),

-- ==================== VOLLEY (28) ====================
('Split-Step Volley Intro','Practice the split-step timing at the net and punch the first volley to an open target.','volley','beginner','pairs',10,'volley_exchange'),
('Forehand Volley Basics','Short, punched forehand volleys aimed at the T or sideline from a fixed net position.','volley','beginner','pairs',10,'volley_exchange'),
('Backhand Volley Basics','Punch backhand volleys using a short firm grip. No swing — just block and redirect.','volley','beginner','pairs',10,'volley_exchange'),
('Two-Player Volley-to-Volley','Both players at net exchanging volleys softly. Focus on control and positioning.','volley','beginner','pairs',10,'volley_exchange'),
('Angled Volley to Target','Place cones in corners; player at net punches volleys to the cone from a feed.','volley','beginner','individual',10,'volley_exchange'),
('High Volley Put-Away','Coach lobs short; player at net puts away a high volley winner.','volley','beginner','pairs',10,'overhead'),
('Approach and First Volley','Approach shot brings player to service line; hit a deep first volley to set up winner.','volley','beginner','pairs',12,'approach_volley'),
('Net Touch Volley','Both players start at baseline, approach together, and exchange volleys at close range.','volley','beginner','pairs',12,'volley_exchange'),
('Reflex Volley Rapid-Fire','Coach feeds rapid volleys from the service line. Player reacts with controlled punches.','volley','intermediate','pairs',10,'volley_exchange'),
('Swinging Volley Forehand','Step into the court and take the high floating ball with a swinging forehand volley.','volley','intermediate','pairs',12,'volley_exchange'),
('Drop Volley Finesse','Absorb the pace of a fast ball at net, dropping a delicate stop volley into the service box.','volley','intermediate','pairs',12,'volley_exchange'),
('Angled Low Volley','Dig out a low ball at net and angle it sharply cross-court to pull the opponent wide.','volley','intermediate','pairs',12,'volley_exchange'),
('Approach + 2 Volleys','Approach shot, then first deep volley, then put-away volley. Three-shot combination.','volley','intermediate','pairs',15,'approach_volley'),
('Overhead Smash Sequence','Player backpedals for overhead from net position after a lob. Emphasize footwork.','volley','intermediate','pairs',12,'overhead'),
('Volley Pattern: Angle then DTL','First volley cross-court angle, second volley down the line for winner.','volley','intermediate','pairs',15,'volley_exchange'),
('Serve-Volley Simulation','Serve from baseline, run in, split-step at service line, volley first ball.','volley','intermediate','pairs',15,'approach_volley'),
('Half-Volley Recovery','After being passed, dig out a half-volley at the feet and recover to a strong net position.','volley','intermediate','pairs',12,'volley_exchange'),
('Back-Pedal Overhead','Lob from opponent; player backpedals correctly using small shuffle steps and smashes.','volley','intermediate','pairs',12,'overhead'),
('Behind-the-Back Recovery Volley','Coach feeds directly at the player; player must redirect using a backhand reflex volley.','volley','intermediate','pairs',10,'volley_exchange'),
('Slice Drop Volley Touch','Use extreme slice under the ball to create a volley that barely clears and dies quickly.','volley','intermediate','pairs',12,'volley_exchange'),
('Poach Practice','In doubles formation, one player poaches on the partner''s serve to intercept the return.','volley','advanced','group',15,'volley_exchange'),
('Pressure Volley Exchange','Rapid-fire feed from 3 m away; player volleys 20 consecutive balls without a miss.','volley','advanced','pairs',12,'volley_exchange'),
('Angle Volley Winner','Set up with a deep first volley then angle a winner wide to the open court.','volley','advanced','pairs',12,'volley_exchange'),
('Overhead Under Pressure','Player holds net, partner lobs repeatedly. Put away 5 consecutive overheads to win the point.','volley','advanced','pairs',12,'overhead'),
('Serve + Volley Advanced','Serve a kick to the backhand, rush in, and volley the weak return to an open court.','volley','advanced','pairs',15,'approach_volley'),
('Low Volley Angle Contest','Feed at the feet; player must create an angle with the low ball to make the opponent run.','volley','advanced','pairs',12,'volley_exchange'),
('Drop Volley vs Lob','After drop volley, opponent lobs; player recovers and hits overhead. Alternating pattern.','volley','advanced','pairs',15,'lob_overhead'),
('Volley Marathon','Hold net against a baseline player hitting groundstrokes. First to 10 volleys without error wins.','volley','advanced','pairs',15,'volley_exchange'),

-- ==================== FOOTWORK (30) ====================
('Shadow Footwork Basics','Move side-to-side in athletic stance without a ball, practicing split-step timing.','footwork','beginner','individual',10,'footwork_agility'),
('Side-to-Side Shuffle','Shuffle from sideline to sideline 5 times, maintaining low, athletic posture throughout.','footwork','beginner','individual',10,'footwork_agility'),
('Cone Touch Drill','Place 4 cones on the baseline; touch each cone in sequence then recover to center.','footwork','beginner','individual',10,'footwork_agility'),
('Forward-Back Movement','Move forward to attack short ball, recover backward, repeat 10 times per set.','footwork','beginner','individual',10,'footwork_agility'),
('Spider Drill Classic','Sprint to all 5 positions on the baseline and back to center. Time and improve.','footwork','beginner','individual',12,'footwork_agility'),
('Crossover Step Practice','Practice crossover steps (not side shuffle) to cover wide balls quickly.','footwork','beginner','individual',10,'footwork_agility'),
('Split Step Timing','Ball machine or coach feed at irregular intervals; player practices split-step timing only.','footwork','beginner','individual',10,'footwork_agility'),
('Recovery to Center','After each shot, sprint back to center mark. Penalize late recoveries.','footwork','beginner','pairs',10,'footwork_agility'),
('T-Drill','Sprint to net, sideline, center, other sideline, back to baseline T. Classic agility test.','footwork','beginner','individual',12,'footwork_agility'),
('Ladder Warm-Up','Quick-feet agility ladder at courtside. 5 patterns: high knees, in-out, lateral, ickey, Ali shuffle.','footwork','beginner','individual',10,'footwork_agility'),
('Wide-Ball Recovery','Coach feeds wide alternating; player sprints, hits, and recovers between each.','footwork','intermediate','individual',12,'defensive_reset'),
('Figure-8 Footwork','Sprint in a figure-8 pattern around two cones spaced 5 m apart. 5 sets.','footwork','intermediate','individual',12,'footwork_agility'),
('Approach Step Drill','Practice the approach-step sequence: split, load, push into shot, close to net.','footwork','intermediate','individual',10,'approach_net'),
('Angle Run Drill','Two wide balls played alternately; player runs in opposite directions covering maximum court.','footwork','intermediate','pairs',15,'defensive_reset'),
('First-Step Reaction','Coach points left/right at random; player explodes into first crossover step immediately.','footwork','intermediate','individual',10,'footwork_agility'),
('Around-the-Outside','Sprint around a cone placed just outside the singles sideline after each ball.','footwork','intermediate','pairs',12,'footwork_agility'),
('Box Drill Advanced','Move in a square pattern: forward, side, back, side. Add racket swing at each corner.','footwork','intermediate','individual',12,'footwork_agility'),
('Pressure Wide-Ball Sprint','Opponent hits alternating wide forehands and backhands; player must reach every ball.','footwork','intermediate','pairs',15,'defensive_reset'),
('Net-Rush Footwork','After hitting groundstroke, sprint to net position, split-step, volley, recover.','footwork','intermediate','pairs',12,'approach_net'),
('Defensive Slide','Practice sliding (on clay) to reach extreme wide balls while maintaining balance.','footwork','intermediate','individual',12,'defensive_reset'),
('Marathon Rally Movement','Sustain a 30-shot rally, recovering to center mark completely after every single shot.','footwork','advanced','pairs',15,'baseline_rally'),
('Spider Drill Competition','Two players race the spider drill simultaneously on opposite sides. Best time wins.','footwork','advanced','group',12,'footwork_agility'),
('Three-Ball Movement','Coach feeds 3 balls in rapid succession to different locations. Recover between each.','footwork','advanced','individual',12,'footwork_agility'),
('Defense-to-Offense Transition','Start wide and defensive; recover and transition to offense within 2 shots.','footwork','advanced','pairs',15,'defensive_reset'),
('Volley-Retreat-Smash','At net, retreat for lob, smash, recover to net. Repeat 10 times without miss.','footwork','advanced','pairs',12,'lob_overhead'),
('Full-Court Chase','Coach feeds balls to all 4 corners in sequence. Player must reach and return every ball.','footwork','advanced','individual',15,'footwork_agility'),
('Explosive First Step','Resistance band on waist; partner pulls backward, then releases — player explodes forward.','footwork','advanced','pairs',10,'footwork_agility'),
('Non-Stop Point Simulation','Play points with a coach feeding. After every shot, sprint to a cone and return.','footwork','advanced','pairs',15,'defensive_reset'),
('Counterattack Run Drill','Retrieve a defensive ball at full sprint, then recover and strike an offensive shot.','footwork','advanced','pairs',15,'defensive_reset'),
('High-Intensity Court Sprint','Sprint baseline to net and back 10 times with 15 seconds rest between reps.','footwork','advanced','individual',15,'footwork_agility'),

-- ==================== RETURN (26) ====================
('Return Stance Basics','Practice the return ready position: weight forward, early split-step as ball is tossed.','return','beginner','pairs',10,'return_cc'),
('Flat Return Cross-Court','Block a moderate serve back cross-court using a compact, firm swing.','return','beginner','pairs',10,'return_cc'),
('Return Down the Line Intro','Practice redirecting the return down the line when server leaves an opening.','return','beginner','pairs',10,'return_dtl'),
('Chip-and-Charge Return','Chip a slice return low and short, then rush the net behind it.','return','beginner','pairs',12,'return_cc'),
('Return Consistency Challenge','Hit 20 returns in a row to a designated zone. Count successful placements.','return','beginner','pairs',15,'return_cc'),
('Split-Step Timing for Return','Focus only on the split-step: time it perfectly as the server hits the ball.','return','beginner','pairs',10,'return_cc'),
('Forehand Return Drill','Server targets only the forehand wing; returner works on offensive forehand returns.','return','beginner','pairs',12,'return_cc'),
('Backhand Return Drill','Server targets only the backhand wing; returner drives compact backhand returns.','return','beginner','pairs',12,'return_cc'),
('Lob Return vs Serve-Volley','Against a serve-and-volley server, practice lobbing the return over the net rusher.','return','intermediate','pairs',12,'lob_overhead'),
('Return Wide Serve Forehand','Sprint to reach a wide serve on the forehand side and return aggressively.','return','intermediate','pairs',12,'return_cc'),
('Return Wide Serve Backhand','Reach a wide serve on the backhand side and drive the return cross-court.','return','intermediate','pairs',12,'return_cc'),
('Return Body Serve','Practice absorbing a body serve and redirecting it away from the server.','return','intermediate','pairs',12,'return_cc'),
('Return + Recover Rally','Return the serve, then play out the point from the rally. Emphasize transition.','return','intermediate','pairs',15,'return_cc'),
('Return Kick Serve to Backhand','The high-bouncing kick serve is directed to the backhand; return aggressively cross-court.','return','intermediate','pairs',12,'return_cc'),
('T-Serve Return Pattern','Return serves to the T and redirect them to the open court using crosscourt angles.','return','intermediate','pairs',15,'return_dtl'),
('Return + Net Attack','Return aggressively then follow the return into the net for a volley finish.','return','intermediate','pairs',15,'return_cc'),
('Second Serve Attack','Attack the second serve with a full swing rather than a passive block.','return','intermediate','pairs',12,'return_cc'),
('Return Neutral then Attack','Block first return deep, then attack the second ball aggressively.','return','intermediate','pairs',15,'return_cc'),
('Return Winner Hunt','Play 10 return points. Score 2 points for a return winner, 1 for a winner within 3 shots.','return','advanced','pairs',15,'return_cc'),
('Aggressive Return of First Serve','Step in and take the first serve early, driving it back to a corner at maximum pace.','return','advanced','pairs',15,'return_cc'),
('Return Placement Under Pressure','Fast serves to random locations; returner must place returns to predetermined zones.','return','advanced','pairs',15,'return_dtl'),
('Return + Counterattack Combo','Return deep cross-court, receive a reply, then explode into an offensive groundstroke winner.','return','advanced','pairs',15,'return_cc'),
('Wide-Serve Acute Angle Return','Reach a very wide serve and angle the return acutely to the open court.','return','advanced','pairs',12,'return_cc'),
('Second Serve Dictation','Win return points outright or dictate the 3rd shot. Play 20 second-serve points.','return','advanced','pairs',15,'return_cc'),
('Return Decision Game','Server calls after toss: T or wide. Returner has 1 second to pick a shot direction.','return','advanced','pairs',15,'return_dtl'),
('Return Pattern Practice','Practice 3 preset return patterns: CC, DTL, lob. Rotate on each serve received.','return','advanced','pairs',15,'return_cc'),

-- ==================== GROUNDSTROKES (36) ====================
('Crosscourt Baseline Rally','Sustained cross-court rally from the baseline. Both players maintain depth and consistency.','groundstrokes','beginner','pairs',10,'baseline_rally'),
('Depth Target Drill','Place cones 1 m from the baseline. Hit all groundstrokes past the cones for depth.','groundstrokes','beginner','pairs',12,'baseline_rally'),
('Alternate Forehand-Backhand','Coach feeds alternately to forehand and backhand. Player must recover to center between.','groundstrokes','beginner','individual',10,'baseline_rally'),
('Half-Court Rally','Confine rally to one half of the court (deuce or ad side) for accuracy and control.','groundstrokes','beginner','pairs',12,'half_court'),
('Groundstroke Warm-Up','Easy-paced rally from baseline to calibrate timing, spin, and depth. No pressure.','groundstrokes','beginner','pairs',8,'baseline_rally'),
('Feeding Basket Rally','Coach feeds 20 balls to alternating corners; player hits each to a consistent target.','groundstrokes','beginner','individual',10,'baseline_rally'),
('Centerline Rally','Both players keep balls between the singles sidelines and the center service line.','groundstrokes','beginner','pairs',10,'baseline_rally'),
('Slow-Ball Deep Drive','Feed very slow, high balls; player practices driving them deep with topspin.','groundstrokes','beginner','pairs',10,'baseline_rally'),
('Direction Control Rally','Player hits 5 cross-court, then 5 down the line, cycling between directions.','groundstrokes','beginner','pairs',12,'dtl_fh'),
('Crosscourt Attack','Both players push the cross-court rally harder, trying to open the court gradually.','groundstrokes','intermediate','pairs',12,'crosscourt_fh'),
('DTL Pattern Practice','Open cross-court, then redirect down the line. Classic point-ending pattern.','groundstrokes','intermediate','pairs',15,'dtl_fh'),
('Figure-8 Groundstroke','Player hits cross-court, opponent returns down the line. Pattern creates diagonal movement.','groundstrokes','intermediate','pairs',15,'crosscourt_fh'),
('Short Ball Attack','Feed a short ball to the service line; player approaches and finishes the point.','groundstrokes','intermediate','pairs',12,'approach_net'),
('Heavy Ball vs Heavy Ball','Both players generate maximum topspin, creating a physically demanding baseline exchange.','groundstrokes','intermediate','pairs',15,'baseline_rally'),
('Topspin vs Slice','One player hits topspin, the other replies with slice. Maintain consistency for 20 shots.','groundstrokes','intermediate','pairs',15,'baseline_rally'),
('Groundstroke Under Pressure','Coach hits random deep and wide balls; player must chase and recover every shot.','groundstrokes','intermediate','individual',15,'defensive_reset'),
('Deuce Side Half-Court','Contain rally entirely to the deuce side. Exploit angles within the confined space.','groundstrokes','intermediate','pairs',12,'half_court'),
('Ad Side Half-Court','Contain rally to the ad side. Work the backhand-to-backhand diagonal.','groundstrokes','intermediate','pairs',12,'half_court'),
('Lob vs Overhead Game','One player lobs continuously; the other puts away overheads. Switch after 10 balls.','groundstrokes','intermediate','pairs',12,'lob_overhead'),
('Drop Shot vs Retrieve','One player hits drop shots; the other sprints to retrieve and pass. Alternate roles.','groundstrokes','intermediate','pairs',15,'drop_shot'),
('Transition Drill','Start at net, retreat to baseline, play out the point from the rally.','groundstrokes','intermediate','pairs',15,'baseline_rally'),
('High-Intensity 10-Shot Rally','Both players agree to go full pace for exactly 10 shots, then pause and reset.','groundstrokes','intermediate','pairs',15,'baseline_rally'),
('Baseline Endurance Rally','Sustain a cross-court rally for 50 shots. Count aloud. Any miss restarts from 1.','groundstrokes','intermediate','pairs',15,'baseline_rally'),
('Offensive Baseline Pattern','Cross-court, cross-court, short angle, finish. 4-shot pattern played at high pace.','groundstrokes','advanced','pairs',15,'crosscourt_fh'),
('Defense to Offense','Receive a hard, deep ball, reset defensively, then transition and attack the next short ball.','groundstrokes','advanced','pairs',15,'defensive_reset'),
('Angles Only Rally','Both players can only use acute cross-court angles. No down-the-line allowed.','groundstrokes','advanced','pairs',15,'crosscourt_fh'),
('No-Man''s Land Drill','Both players must stay between service line and baseline. Unusual positions create challenges.','groundstrokes','advanced','pairs',15,'baseline_rally'),
('Kick Ball High-Bounce','Coach feeds heavy topspin balls; player must step back, let it bounce high, and attack.','groundstrokes','advanced','individual',12,'baseline_rally'),
('Inside-Out Pattern','Move around backhand, inside-out forehand, inside-in forehand winner. 3-shot sequence.','groundstrokes','advanced','pairs',15,'inside_out'),
('Short Cross + DTL Finish','Short cross-court angle then redirect sharply down the line for an outright winner.','groundstrokes','advanced','pairs',15,'dtl_fh'),
('Full-Court Pattern Game','Play points only using preset shot patterns. First player to break pattern loses the point.','groundstrokes','advanced','pairs',15,'full_court'),
('Serve + Groundstroke Pattern','Serve to a target, attack the return, then play out the point with an aggressive pattern.','groundstrokes','advanced','pairs',15,'baseline_rally'),
('Groundstroke Accuracy Contest','20 balls to each corner target. Score 2 points inside cone, 1 in zone, 0 outside zone.','groundstrokes','advanced','individual',15,'baseline_rally'),
('Recovery Champion','Opponent hits every ball wide; player must sprint, reach, and hit a quality shot every time.','groundstrokes','advanced','pairs',15,'defensive_reset'),
('Pro Baseline Game','Play baseline-only points. Net approaches not allowed. First to 7 wins.','groundstrokes','advanced','pairs',15,'baseline_rally'),
('Topspin Bomb Rally','Both players maximize topspin RPM and depth. No pace — pure spin and bounce height.','groundstrokes','advanced','pairs',12,'baseline_rally'),

-- ==================== MATCH PLAY (40) ====================
('Mini-Tennis Game','Play points inside the service boxes only. Focus on touch, angles, and reactions.','match play','beginner','pairs',12,'mini_tennis'),
('First to 7 Points','Informal scoring game first to 7 points. No deuce. Coach can feed the first ball.','match play','beginner','pairs',15,'baseline_rally'),
('Serve + 1 Game','Server gets 2 points for winning the point within 1 shot after return. Returner gets 1 for longer.','match play','beginner','pairs',15,'serve_t_d'),
('Cross-Court Only Points','Play points where all balls must land cross-court. Down-the-line shots concede the point.','match play','beginner','pairs',15,'crosscourt_fh'),
('One-Serve Game','Each player gets one serve per point. Develops serve accuracy.','match play','beginner','pairs',15,'serve_t_d'),
('Consistency Game','First player to make 5 unforced errors loses the game. Emphasizes mental control.','match play','beginner','pairs',12,'baseline_rally'),
('Cooperative Rally then Point','Start with 10 cooperative shots then play out the point. Warm up then compete.','match play','beginner','pairs',15,'baseline_rally'),
('Half-Court Singles','Play points using only half the court (deuce side). Accuracy and placement are key.','match play','beginner','pairs',12,'half_court'),
('Tiebreak Practice','Play 7-point tiebreaks continuously. Practice tiebreak scoring and pressure situations.','match play','intermediate','pairs',15,'baseline_rally'),
('Serve + Pattern Points','Server must use a preset pattern (e.g. wide serve + crosscourt forehand). Score normally.','match play','intermediate','pairs',15,'serve_wide_d'),
('Return Game','Returner starts every point with the serve. Server tries to win; returner has a target.','match play','intermediate','pairs',15,'return_cc'),
('Approach Shot Game','Any short ball must be approached. Points won at net score double.','match play','intermediate','pairs',15,'approach_net'),
('Handicap Game','Stronger player starts every game at 0-30 or 0-40. Levels the playing field.','match play','intermediate','pairs',15,'baseline_rally'),
('Doubles Points','4 players play doubles points (no serve). Coach feeds to start. Focus on positioning.','match play','intermediate','group',15,'volley_exchange'),
('First Ball Attack Game','Any ball landing short of service line must be attacked. If player doesn''t attack, loses point.','match play','intermediate','pairs',15,'approach_net'),
('No-Volley Game','Player loses point if they step inside the service box. Baseline-only competition.','match play','intermediate','pairs',15,'baseline_rally'),
('Ad-Side Only Game','Play all points exclusively from the ad court (left side). Both deuce and ad points played there.','match play','intermediate','pairs',15,'half_court'),
('Serve and Dictate','Server''s goal: win the point within 4 shots. Returner''s goal: survive those 4 shots.','match play','intermediate','pairs',15,'serve_t_d'),
('Pressure Point Game','Play sudden-death points only. One ball, one chance. Simulate match pressure moments.','match play','intermediate','pairs',10,'baseline_rally'),
('Two-Bounce Rule','After the serve, both players must let the ball bounce twice before volleying. Promotes patience.','match play','intermediate','pairs',15,'baseline_rally'),
('3-Ball Feed Scoring','Coach feeds 3 balls per point. First is a setup, second is neutral, third is for the finish.','match play','intermediate','group',15,'baseline_rally'),
('Competitive Sets','Play full sets with proper scoring. Emphasize routine, breathing, and focus between points.','match play','advanced','pairs',20,'baseline_rally'),
('Match Simulation w/ Patterns','Play full match-style points but each player must use their practiced pattern on the first 3 shots.','match play','advanced','pairs',20,'full_court'),
('Sudden-Death Tiebreak','First to 5 points in a tiebreak. Every point is sudden death. High-pressure training.','match play','advanced','pairs',15,'baseline_rally'),
('Serve-Volley vs Baseliner','One player serves and volleys every point; the other passes. Alternate roles every 10 points.','match play','advanced','pairs',15,'approach_volley'),
('Return Game Advanced','Returner has 4 chances to win the point within 2 shots of the return. Develop aggression.','match play','advanced','pairs',15,'return_cc'),
('Scenario Points','Coach announces a match scenario (3rd set, 5-5, 30-40). Players must react to the pressure.','match play','advanced','pairs',15,'baseline_rally'),
('Drop Shot vs Defense Game','One player only uses drop shots and short angles. Other only retrieves and passes.','match play','advanced','pairs',15,'drop_shot'),
('Lob vs Smash Game','One player at net; other plays only lobs. Net player can only smash. Play 10-point sets.','match play','advanced','pairs',15,'lob_overhead'),
('Pattern Breaking Challenge','Player 1 plays a set pattern; player 2 tries to break it by anticipating the next shot.','match play','advanced','pairs',15,'full_court'),
('Serve + 2 Attack Game','Server plays predetermined serve direction then attacks on the 3rd shot. Defender must adapt.','match play','advanced','pairs',15,'serve_t_d'),
('Full Match Competitive','Play a proper match: 6-game set with deuce, tiebreak at 6-6. Focused on all aspects.','match play','advanced','pairs',30,'full_court'),
('Point Construction Workshop','Play points slowly, pausing to discuss shot selection after each point. Coaching focus.','match play','advanced','group',20,'full_court'),
('Zone Scoring Game','Divide court into scoring zones. Shots landing in better zones earn more points per rally.','match play','advanced','pairs',15,'full_court'),
('Mental Toughness Set','Play a full set where every unforced error costs an extra point. Mental discipline required.','match play','advanced','pairs',20,'baseline_rally'),
('Night-Mode Speed Points','Fastest possible 20-point set. First to 20. No breaks, no let serves. Full intensity.','match play','advanced','pairs',15,'baseline_rally'),
('Alternate Serve Game','Each player serves one point at a time (alternate service). Constant switching of rhythm.','match play','advanced','pairs',15,'serve_t_d'),
('Approach + Overhead Game','Bonus point for winning an approach-volley-overhead sequence within one point.','match play','advanced','pairs',15,'lob_overhead'),
('One-Wing Only Match','Player can only use one wing (forehand or backhand) for groundstrokes. Forces discipline.','match play','advanced','pairs',15,'baseline_rally'),
('Competitive Coaching Set','Coach calls out tactical advice after each point. Player must immediately implement.','match play','advanced','group',20,'full_court');
