import { useState, useEffect, useRef, useCallback } from 'react'
import { useNavigate } from 'react-router-dom'
import { Play, Lock, ChevronRight, ChevronLeft } from 'lucide-react'
import AddonPaywallModal from '../../components/AddonPaywallModal'
import CardArt, { HeroArt } from '../../components/dashboard/CardArt'
import { MODULES } from '../../config/modules'
import { MODULE_CARDS, MODULES_WITH_CONTENT, DRILL_CATEGORIES } from '../../config/catalog'
import { useUserModules } from '../../hooks/useUserModules'

// ─────────────────────────────────────────────────────────────────────────────
// Netflix-style browse screen: a featured hero, then one horizontal row per
// module with vertical poster cards inside it.
//
// Rows come from config/modules.js; the cards inside them from config/catalog.js.
// ─────────────────────────────────────────────────────────────────────────────

// ── Poster card ─────────────────────────────────────────────────────────────

// Artwork resolves by convention to /cards/<key>.webp, generated by
// scripts/generate_card_art.mjs. If a card has no image yet — or the file fails
// to load — the SVG in CardArt takes over, so the row never renders a gap.
function PosterCard({ card, vi = 0, locked, onOpen }) {
  const [artFailed, setArtFailed] = useState(false)
  const src = card.image ?? `/cards/${card.key}.webp`

  return (
    <button
      onClick={() => onOpen(card)}
      className="group relative shrink-0 w-[132px] sm:w-[160px] snap-start rounded-xl overflow-hidden bg-gray-900 text-left transition duration-300 hover:scale-[1.04] hover:z-10 focus:outline-none focus-visible:ring-2 focus-visible:ring-green-500"
      aria-label={locked ? `${card.title} — locked` : card.title}
    >
      <div className="relative aspect-[2/3]">
        {artFailed ? (
          <CardArt card={card} vi={vi} />
        ) : (
          <img
            src={src}
            alt=""
            loading="lazy"
            onError={() => setArtFailed(true)}
            className="w-full h-full object-cover"
          />
        )}

        {/* Scrim keeps the title readable over any artwork */}
        <div className="absolute inset-x-0 bottom-0 h-2/3 bg-gradient-to-t from-black/90 via-black/40 to-transparent" />

        {locked && (
          <div className="absolute inset-0 bg-gray-950/55 backdrop-blur-[1px] flex items-start justify-end p-2">
            <span className="w-7 h-7 rounded-full bg-black/70 flex items-center justify-center">
              <Lock className="w-3.5 h-3.5 text-amber-300" />
            </span>
          </div>
        )}

        <div className="absolute inset-x-0 bottom-0 p-3">
          <p className="text-white font-bold text-[13px] leading-tight line-clamp-2">
            {card.title}
          </p>
          <p className="text-gray-400 text-[10px] mt-0.5 font-medium">
            {card.count != null ? `${card.count} drills` : card.subtitle ?? 'Soon'}
          </p>
        </div>

        {/* Hover affordance, pointer devices only */}
        <div className="absolute inset-0 hidden sm:flex items-center justify-center opacity-0 group-hover:opacity-100 transition-opacity">
          <span className="w-11 h-11 rounded-full bg-white/15 backdrop-blur-sm flex items-center justify-center">
            {locked ? (
              <Lock className="w-4 h-4 text-white" />
            ) : (
              <Play className="w-4 h-4 text-white fill-white ml-0.5" />
            )}
          </span>
        </div>
      </div>
    </button>
  )
}

// ── Row ─────────────────────────────────────────────────────────────────────

function Row({ module, cards, locked, onOpen, onTitleClick }) {
  const scroller = useRef(null)
  const [atStart, setAtStart] = useState(true)
  const [atEnd, setAtEnd] = useState(false)

  const sync = useCallback(() => {
    const el = scroller.current
    if (!el) return
    setAtStart(el.scrollLeft <= 4)
    setAtEnd(el.scrollLeft + el.clientWidth >= el.scrollWidth - 4)
  }, [])

  useEffect(() => {
    sync()
    const el = scroller.current
    if (!el) return
    el.addEventListener('scroll', sync, { passive: true })
    window.addEventListener('resize', sync)
    return () => {
      el.removeEventListener('scroll', sync)
      window.removeEventListener('resize', sync)
    }
  }, [sync])

  function nudge(direction) {
    const el = scroller.current
    if (!el) return
    el.scrollBy({ left: direction * el.clientWidth * 0.8, behavior: 'smooth' })
  }

  return (
    <section className="mb-7 sm:mb-9">
      <div className="flex items-center justify-between px-4 sm:px-6 mb-2.5">
        <button
          onClick={onTitleClick}
          className="group flex items-center gap-1.5 min-w-0"
        >
          <h2 className="text-white font-bold text-[15px] sm:text-lg truncate">
            {module.title}
          </h2>
          {locked && <Lock className="w-3.5 h-3.5 text-amber-400 shrink-0" />}
          <ChevronRight className="w-4 h-4 text-gray-600 group-hover:text-green-400 group-hover:translate-x-0.5 transition shrink-0" />
        </button>

        {/* Arrows are a pointer-device affordance; touch users just swipe */}
        <div className="hidden sm:flex items-center gap-1">
          <button
            onClick={() => nudge(-1)}
            disabled={atStart}
            aria-label={`Scroll ${module.title} left`}
            className="w-7 h-7 rounded-full bg-gray-800/80 flex items-center justify-center text-gray-400 hover:text-white hover:bg-gray-700 disabled:opacity-25 disabled:pointer-events-none transition"
          >
            <ChevronLeft className="w-4 h-4" />
          </button>
          <button
            onClick={() => nudge(1)}
            disabled={atEnd}
            aria-label={`Scroll ${module.title} right`}
            className="w-7 h-7 rounded-full bg-gray-800/80 flex items-center justify-center text-gray-400 hover:text-white hover:bg-gray-700 disabled:opacity-25 disabled:pointer-events-none transition"
          >
            <ChevronRight className="w-4 h-4" />
          </button>
        </div>
      </div>

      {/* scroll-pl must match the horizontal padding: with `snap-mandatory` the
          browser aligns the first card to the scrollport edge and swallows the
          padding, leaving the row visibly out of line with its own heading. */}
      <div
        ref={scroller}
        className="flex gap-2.5 sm:gap-3 overflow-x-auto no-scrollbar snap-x snap-mandatory scroll-pl-4 sm:scroll-pl-6 px-4 sm:px-6 pb-1"
      >
        {cards.map((card, i) => (
          <PosterCard key={card.key} card={card} vi={i} locked={locked} onOpen={onOpen} />
        ))}
      </div>
    </section>
  )
}

// ── Hero ────────────────────────────────────────────────────────────────────

function Hero({ onOpen }) {
  const [artFailed, setArtFailed] = useState(false)

  return (
    <div className="relative w-full h-[300px] sm:h-[380px] overflow-hidden">
      <div className="absolute inset-0">
        {artFailed ? (
          <HeroArt />
        ) : (
          <img
            src="/cards/hero.webp"
            alt=""
            onError={() => setArtFailed(true)}
            className="w-full h-full object-cover"
          />
        )}
      </div>

      {/* Two scrims: bottom for the copy, left for wide screens */}
      <div className="absolute inset-0 bg-gradient-to-t from-gray-950 via-gray-950/55 to-transparent" />
      <div className="absolute inset-0 bg-gradient-to-r from-gray-950/85 via-gray-950/20 to-transparent" />

      <div className="relative h-full flex flex-col justify-end px-4 sm:px-6 pb-6 max-w-lg">
        <span className="text-green-400 text-[10px] font-black uppercase tracking-[0.2em] mb-2">
          Your library
        </span>
        <h1 className="text-white text-[26px] sm:text-4xl font-extrabold leading-[1.1] mb-2">
          280 drills, ready
          <br />
          for your next lesson
        </h1>
        <p className="text-gray-400 text-xs sm:text-sm mb-4 max-w-sm leading-relaxed">
          Every drill with setup, step-by-step instructions, coaching cues and
          court diagrams.
        </p>
        <button
          onClick={() => onOpen(null)}
          className="inline-flex items-center gap-2 bg-white text-gray-900 font-bold text-sm px-5 py-2.5 rounded-lg w-fit hover:bg-gray-200 active:scale-95 transition"
        >
          <Play className="w-4 h-4 fill-gray-900" />
          Browse drills
        </button>
      </div>
    </div>
  )
}

// ── Page ────────────────────────────────────────────────────────────────────

export default function Home() {
  const { hasAccess, loading, refresh } = useUserModules()
  const [paywallModule, setPaywallModule] = useState(null)
  const navigate = useNavigate()

  useEffect(() => {
    const params = new URLSearchParams(window.location.search)
    const sessionId = params.get('session_id')
    if (!sessionId) return

    // Clean the URL immediately so a refresh doesn't re-provision
    navigate('/dashboard', { replace: true })

    fetch('/api/provision-access', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ sessionId }),
    })
      .then((r) => r.json())
      .then((data) => { if (data.success) refresh() })
      .catch(() => {})
  }, [])

  if (loading) return null

  // Owned modules first, locked ones after — locked rows stay visible so they
  // remain a route to purchase rather than disappearing.
  const rows = MODULES.filter((m) => MODULE_CARDS[m.id]?.length)
  const owned = rows.filter((m) => hasAccess(m))
  const lockedRows = rows.filter((m) => !hasAccess(m))

  function openModule(module) {
    if (!hasAccess(module)) {
      if (module.isAddon) return setPaywallModule(module)
      return navigate('/dashboard/settings')
    }
    navigate(module.route)
  }

  function openCard(module, card) {
    if (!hasAccess(module)) {
      if (module.isAddon) return setPaywallModule(module)
      return navigate('/dashboard/settings')
    }
    // Only drills has content behind individual cards today; everything else
    // opens its module page until that content is built.
    if (MODULES_WITH_CONTENT.has(module.id) && card?.key) {
      return navigate(`${module.route}?c=${card.key}`)
    }
    navigate(module.route)
  }

  const drills = MODULES.find((m) => m.id === 'drills')

  return (
    <div className="min-h-full bg-gray-950 pb-10">
      <Hero
        onOpen={() => (drills && hasAccess(drills) ? navigate(drills.route) : navigate('/dashboard/settings'))}
      />

      {/* Rows lift over the hero's lower edge, as on Netflix */}
      <div className="relative -mt-4">
        {[...owned, ...lockedRows].map((module) => (
          <Row
            key={module.id}
            module={module}
            cards={MODULE_CARDS[module.id]}
            locked={!hasAccess(module)}
            onOpen={(card) => openCard(module, card)}
            onTitleClick={() => openModule(module)}
          />
        ))}
      </div>

      {paywallModule && (
        <AddonPaywallModal module={paywallModule} onClose={() => setPaywallModule(null)} />
      )}
    </div>
  )
}
